# Generated by Django 5.2.4 on 2025-07-30 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Chủ đề')),
                ('message', models.TextField(verbose_name='Tin nhắn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
            ],
            options={
                'verbose_name': 'Liên hệ',
                'verbose_name_plural': 'Liên hệ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100, verbose_name='Trường')),
                ('degree', models.CharField(max_length=100, verbose_name='Bằng cấp')),
                ('field_of_study', models.CharField(max_length=100, verbose_name='Chuyên ngành')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='GPA')),
            ],
            options={
                'verbose_name': 'Học vấn',
                'verbose_name_plural': 'Học vấn',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Công ty')),
                ('position', models.CharField(max_length=100, verbose_name='Vị trí')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('description', models.TextField(verbose_name='Mô tả công việc')),
                ('is_current', models.BooleanField(default=False, verbose_name='Hiện tại')),
            ],
            options={
                'verbose_name': 'Kinh nghiệm',
                'verbose_name_plural': 'Kinh nghiệm',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('title', models.CharField(max_length=100, verbose_name='Chức danh')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('about', models.TextField(verbose_name='Giới thiệu')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/', verbose_name='Ảnh đại diện')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Hồ sơ',
                'verbose_name_plural': 'Hồ sơ',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tên dự án')),
                ('description', models.TextField(verbose_name='Mô tả dự án')),
                ('technologies', models.TextField(verbose_name='Công nghệ sử dụng')),
                ('project_type', models.CharField(choices=[('web', 'Web Application'), ('mobile', 'Mobile App'), ('desktop', 'Desktop App'), ('ai', 'AI/Machine Learning'), ('game', 'Game'), ('other', 'Khác')], max_length=20, verbose_name='Loại dự án')),
                ('image', models.ImageField(blank=True, upload_to='projects/', verbose_name='Hình ảnh')),
                ('video', models.FileField(blank=True, upload_to='projects/videos/', verbose_name='Video demo')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('demo_url', models.URLField(blank=True, verbose_name='Demo URL')),
                ('created_date', models.DateField(verbose_name='Ngày tạo')),
                ('featured', models.BooleanField(default=False, verbose_name='Dự án nổi bật')),
            ],
            options={
                'verbose_name': 'Dự án',
                'verbose_name_plural': 'Dự án',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên kỹ năng')),
                ('level', models.CharField(choices=[('beginner', 'Mới bắt đầu'), ('intermediate', 'Trung cấp'), ('advanced', 'Nâng cao'), ('expert', 'Chuyên gia')], max_length=20, verbose_name='Trình độ')),
                ('percentage', models.IntegerField(default=0, verbose_name='Phần trăm thành thạo')),
            ],
            options={
                'verbose_name': 'Kỹ năng',
                'verbose_name_plural': 'Kỹ năng',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Chú thích')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Ảnh dự án',
                'verbose_name_plural': 'Ảnh dự án',
            },
        ),
    ]
