# Generated by Django 5.2.4 on 2025-07-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree_en',
            field=models.CharField(blank=True, help_text='English degree', max_length=100),
        ),
        migrations.AddField(
            model_name='education',
            name='description_en',
            field=models.TextField(blank=True, help_text='English description'),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_en',
            field=models.CharField(blank=True, help_text='English institution', max_length=100),
        ),
        migrations.AddField(
            model_name='education',
            name='location_en',
            field=models.CharField(blank=True, help_text='English location', max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_en',
            field=models.CharField(blank=True, help_text='English company name', max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(blank=True, help_text='English description'),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_title_en',
            field=models.CharField(blank=True, help_text='English job title', max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_en',
            field=models.CharField(blank=True, help_text='English location', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_en',
            field=models.CharField(blank=True, help_text='English address', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name_en',
            field=models.CharField(blank=True, help_text='English name', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='professional_summary_en',
            field=models.TextField(blank=True, help_text='English professional summary'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(blank=True, help_text='English skill name', max_length=50),
        ),
    ]
