# Generated by Django 5.2.4 on 2025-07-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_education_degree_en_education_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('title_en', models.CharField(blank=True, help_text='English project title', max_length=200)),
                ('description', models.TextField(verbose_name='Project Description')),
                ('description_en', models.TextField(blank=True, help_text='English project description')),
                ('video', models.FileField(blank=True, help_text='Upload MP4 video file of the project', null=True, upload_to='project_videos/')),
                ('technologies', models.TextField(help_text='List technologies, frameworks, and libraries used (comma separated)')),
                ('technologies_en', models.TextField(blank=True, help_text='English technologies list')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub Repository')),
                ('live_demo_url', models.URLField(blank=True, verbose_name='Live Demo URL')),
                ('thumbnail', models.ImageField(blank=True, help_text='Project thumbnail image', null=True, upload_to='project_thumbnails/')),
                ('start_date', models.DateField(verbose_name='Project Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Project End Date')),
                ('is_ongoing', models.BooleanField(default=False, verbose_name='Is this project ongoing?')),
                ('is_featured', models.BooleanField(default=False, help_text='Show this project prominently')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-is_featured', 'order', '-start_date'],
            },
        ),
    ]
